In [1]:
# Assignment: Data Doctor
# Objective: Clean a dataset by handling missing values, removing duplicates,
# standardizing text, and explaining why cleaning matters.

import pandas as pd
import numpy as np

# ---------------------------------------------------
# Step 1: Create a Sample Dataset
# ---------------------------------------------------

data = {
    "Name": ["Alice", "bob", "CHARLIE", "alice", "David", "Emma", "bob"],
    "Age": [23, 25, np.nan, 23, 30, np.nan, 25],
    "City": ["New York", "london", "London", "New york", "Paris", "PARIS", "london"],
    "Score": [85, 90, 88, 85, np.nan, 92, 90]
}

df = pd.DataFrame(data)

print("Original Dataset:\n")
display(df)


# ---------------------------------------------------
# Step 2: Handle Missing Values
# ---------------------------------------------------
# Fill missing Age values with mean age
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Fill missing Score values with median score
df["Score"] = df["Score"].fillna(df["Score"].median())

print("\nDataset After Handling Missing Values:\n")
display(df)


# ---------------------------------------------------
# Step 3: Remove Duplicate Records
# ---------------------------------------------------
df = df.drop_duplicates()

print("\nDataset After Removing Duplicates:\n")
display(df)


# ---------------------------------------------------
# Step 4: Standardize Text
# ---------------------------------------------------
# Convert names and cities to consistent format

df["Name"] = df["Name"].str.title()
df["City"] = df["City"].str.title()

print("\nDataset After Standardizing Text:\n")
display(df)


# ---------------------------------------------------
# Step 5: Final Clean Dataset
# ---------------------------------------------------

print("\nFinal Cleaned Dataset:\n")
display(df)


# ---------------------------------------------------
# Why Data Cleaning Matters
# ---------------------------------------------------

print("""
Why Data Cleaning Matters:

1. Real-world datasets often contain missing values, duplicate records,
   and inconsistent text formatting.

2. Cleaning improves data quality and ensures accurate analysis.

3. Handling missing values prevents errors in machine learning models.

4. Removing duplicates avoids biased or misleading results.

5. Standardizing text ensures consistency for grouping, filtering,
   and analysis.
""")

Original Dataset:

      Name   Age      City  Score
0    Alice  23.0  New York   85.0
1      bob  25.0    london   90.0
2  CHARLIE   NaN    London   88.0
3    alice  23.0  New york   85.0
4    David  30.0     Paris    NaN
5     Emma   NaN     PARIS   92.0
6      bob  25.0    london   90.0

Dataset After Handling Missing Values:

      Name   Age      City  Score
0    Alice  23.0  New York   85.0
1      bob  25.0    london   90.0
2  CHARLIE  25.2    London   88.0
3    alice  23.0  New york   85.0
4    David  30.0     Paris   89.0
5     Emma  25.2     PARIS   92.0
6      bob  25.0    london   90.0

Dataset After Removing Duplicates:

      Name   Age      City  Score
0    Alice  23.0  New York   85.0
1      bob  25.0    london   90.0
2  CHARLIE  25.2    London   88.0
3    alice  23.0  New york   85.0
4    David  30.0     Paris   89.0
5     Emma  25.2     PARIS   92.0

Dataset After Standardizing Text:

      Name   Age      City  Score
0    Alice  23.0  New York   85.0
1      Bob  25.0    London   90.0
2  Charlie  25.2    London   88.0
3    Alice  23.0  New York   85.0
4    David  30.0     Paris   89.0
5     Emma  25.2     Paris   92.0

Final Cleaned Dataset:

      Name   Age      City  Score
0    Alice  23.0  New York   85.0
1      Bob  25.0    London   90.0
2  Charlie  25.2    London   88.0
3    Alice  23.0  New York   85.0
4    David  30.0     Paris   89.0
5     Emma  25.2     Paris   92.0

Why Data Cleaning Matters:

1. Real-world datasets often contain missing values, duplicate records,
   and inconsistent text formatting.

2. Cleaning improves data quality and ensures accurate analysis.

3. Handling missing values prevents errors in machine learning models.

4. Removing duplicates avoids biased or misleading results.

5. Standardizing text ensures consistency for grouping, filtering,
   and analysis.